export const EVENT_STARTS_AT = "2024-05-10 15:00:00"
export const AIRDROP_EVENT_LINK = "https://iskra.world/arcade/juicy-adventure"
export const WHITE_PAPER_LINK = "https://grampus-cwc.gitbook.io/gram_voyage"
export const X_LINK = "https://twitter.com/gram_voyage"
export const DISCORD_LINK = "https://discord.gg/tCcahHxFtN"